// trading-app/src/app/auth/register/page.tsx
'use client'

import React, { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { useForm, FormProvider } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { Card } from '@/components/ui/Card'
import { Badge } from '@/components/ui/Badge'
import { RegisterRequest } from '@/types'
import { apiService } from '@/services/api'
import toast from 'react-hot-toast'
import { cn } from '@/lib/utils'

// Step 1: Basic Information Schema
const basicInfoSchema = z.object({
  firstName: z.string().min(2, 'First name must be at least 2 characters').max(50),
  lastName: z.string().min(2, 'Last name must be at least 2 characters').max(50),
  email: z.string().email('Invalid email address'),
  phone: z.string().regex(/^[+]?[0-9]{10,15}$/, 'Invalid phone number'),
  dateOfBirth: z.string().refine((date) => {
    const birthDate = new Date(date)
    const today = new Date()
    const age = today.getFullYear() - birthDate.getFullYear()
    return age >= 18
  }, 'You must be at least 18 years old'),
})

// Step 2: Address Information Schema
const addressInfoSchema = z.object({
  street: z.string().min(5, 'Street address must be at least 5 characters').max(100),
  city: z.string().min(2, 'City must be at least 2 characters').max(50),
  state: z.string().min(2, 'State must be at least 2 characters').max(50),
  zipCode: z.string().regex(/^[0-9]{5}(-[0-9]{4})?$/, 'Invalid ZIP code'),
  country: z.string().min(2, 'Country must be at least 2 characters').max(50),
})

// Step 3: Security Settings Schema
const securitySchema = z.object({
  password: z.string().min(8, 'Password must be at least 8 characters'),
  confirmPassword: z.string(),
  acceptTerms: z.boolean().refine((val) => val === true, 'You must accept the terms and conditions'),
}).refine((data) => data.password === data.confirmPassword, {
  message: "Passwords don't match",
  path: ['confirmPassword'],
})

// Combined schema for form validation
const registerSchema = z.intersection(
  basicInfoSchema,
  z.intersection(addressInfoSchema, securitySchema)
)

type RegisterFormData = z.infer<typeof registerSchema>

export default function RegisterPage() {
  const router = useRouter()
  const [currentStep, setCurrentStep] = useState(1)
  const [isLoading, setIsLoading] = useState(false)
  const [passwordStrength, setPasswordStrength] = useState(0)

  const methods = useForm<RegisterFormData>({
    resolver: zodResolver(registerSchema),
    mode: 'onChange',
  })

  const {
    register,
    handleSubmit,
    formState: { errors, isValid },
    watch,
    trigger,
  } = methods

  const password = watch('password', '')

  // Calculate password strength
  React.useEffect(() => {
    if (!password) {
      setPasswordStrength(0)
      return
    }

    let strength = 0
    if (password.length >= 8) strength++
    if (password.length >= 12) strength++
    if (/[a-z]/.test(password)) strength++
    if (/[A-Z]/.test(password)) strength++
    if (/[0-9]/.test(password)) strength++
    if (/[^a-zA-Z0-9]/.test(password)) strength++

    setPasswordStrength(strength)
  }, [password])

  const getPasswordStrengthText = () => {
    switch (passwordStrength) {
      case 0:
      case 1:
        return 'Weak'
      case 2:
        return 'Fair'
      case 3:
        return 'Good'
      case 4:
        return 'Strong'
      case 5:
      case 6:
        return 'Very Strong'
      default:
        return 'Weak'
    }
  }

  const getPasswordStrengthColor = () => {
    switch (passwordStrength) {
      case 0:
      case 1:
        return 'bg-danger-500'
      case 2:
        return 'bg-warning-500'
      case 3:
        return 'bg-yellow-500'
      case 4:
        return 'bg-success-500'
      case 5:
      case 6:
        return 'bg-success-600'
      default:
        return 'bg-danger-500'
    }
  }

  const nextStep = async () => {
    let fieldsToValidate: string[] = []
    
    switch (currentStep) {
      case 1:
        fieldsToValidate = ['firstName', 'lastName', 'email', 'phone', 'dateOfBirth']
        break
      case 2:
        fieldsToValidate = ['street', 'city', 'state', 'zipCode', 'country']
        break
      case 3:
        fieldsToValidate = ['password', 'confirmPassword', 'acceptTerms']
        break
    }

    const isStepValid = await trigger(fieldsToValidate as any)
    if (isStepValid) {
      setCurrentStep(currentStep + 1)
    }
  }

  const previousStep = () => {
    setCurrentStep(currentStep - 1)
  }

  const onSubmit = async (data: RegisterFormData) => {
    setIsLoading(true)
    
    try {
      const response = await apiService.register(data)
      toast.success('Registration successful! Please check your email for verification.')
      setTimeout(() => {
        router.push('/auth/login')
      }, 2000)
    } catch (error: any) {
      toast.error(error.message || 'Registration failed. Please try again.')
    } finally {
      setIsLoading(false)
    }
  }

  const getStepTitle = () => {
    switch (currentStep) {
      case 1:
        return 'Personal Information'
      case 2:
        return 'Address Details'
      case 3:
        return 'Security Settings'
      default:
        return 'Registration'
    }
  }

  const getStepDescription = () => {
    switch (currentStep) {
      case 1:
        return 'Tell us about yourself'
      case 2:
        return 'Where should we send your documents?'
      case 3:
        return 'Create a secure password for your account'
      default:
        return 'Complete your registration'
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 to-primary-100 dark:from-gray-900 dark:to-gray-800 flex items-center justify-center p-4">
      <div className="w-full max-w-2xl">
        {/* Logo and App Name */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-primary-600 rounded-full mb-4">
            <svg
              className="w-8 h-8 text-white"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"
              />
            </svg>
          </div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
            TradePro
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            Create your professional trading account
          </p>
        </div>

        {/* Progress Indicator */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-4">
            {[1, 2, 3].map((step) => (
              <div key={step} className="flex items-center">
                <div
                  className={cn(
                    'w-10 h-10 rounded-full flex items-center justify-center text-sm font-medium',
                    step <= currentStep
                      ? 'bg-primary-600 text-white'
                      : 'bg-gray-200 text-gray-500 dark:bg-gray-700 dark:text-gray-400'
                  )}
                >
                  {step}
                </div>
                {step < 3 && (
                  <div
                    className={cn(
                      'flex-1 h-1 mx-4',
                      step < currentStep ? 'bg-primary-600' : 'bg-gray-200 dark:bg-gray-700'
                    )}
                  />
                )}
              </div>
            ))}
          </div>
          <div className="text-center">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">
              {getStepTitle()}
            </h2>
            <p className="text-gray-600 dark:text-gray-400 mt-1">
              {getStepDescription()}
            </p>
          </div>
        </div>

        {/* Registration Form */}
        <Card className="p-8">
          <FormProvider {...methods}>
            <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
              {/* Step 1: Basic Information */}
              {currentStep === 1 && (
                <div className="space-y-6 fade-in">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <Input
                      label="First Name"
                      placeholder="Enter your first name"
                      {...register('firstName')}
                      error={errors.firstName?.message}
                    />
                    <Input
                      label="Last Name"
                      placeholder="Enter your last name"
                      {...register('lastName')}
                      error={errors.lastName?.message}
                    />
                  </div>
                  <Input
                    label="Email Address"
                    type="email"
                    placeholder="Enter your email"
                    {...register('email')}
                    error={errors.email?.message}
                  />
                  <Input
                    label="Phone Number"
                    type="tel"
                    placeholder="+1 (555) 123-4567"
                    {...register('phone')}
                    error={errors.phone?.message}
                  />
                  <Input
                    label="Date of Birth"
                    type="date"
                    {...register('dateOfBirth')}
                    error={errors.dateOfBirth?.message}
                  />
                </div>
              )}

              {/* Step 2: Address Information */}
              {currentStep === 2 && (
                <div className="space-y-6 fade-in">
                  <Input
                    label="Street Address"
                    placeholder="123 Main Street"
                    {...register('street')}
                    error={errors.street?.message}
                  />
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <Input
                      label="City"
                      placeholder="New York"
                      {...register('city')}
                      error={errors.city?.message}
                    />
                    <Input
                      label="State"
                      placeholder="NY"
                      {...register('state')}
                      error={errors.state?.message}
                    />
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <Input
                      label="ZIP Code"
                      placeholder="10001"
                      {...register('zipCode')}
                      error={errors.zipCode?.message}
                    />
                    <Input
                      label="Country"
                      placeholder="United States"
                      {...register('country')}
                      error={errors.country?.message}
                    />
                  </div>
                </div>
              )}

              {/* Step 3: Security Settings */}
              {currentStep === 3 && (
                <div className="space-y-6 fade-in">
                  <div>
                    <Input
                      label="Password"
                      type="password"
                      placeholder="Create a strong password"
                      {...register('password')}
                      error={errors.password?.message}
                    />
                    {password && (
                      <div className="mt-2">
                        <div className="flex items-center justify-between mb-1">
                          <span className="text-sm text-gray-600 dark:text-gray-400">
                            Password Strength
                          </span>
                          <span className="text-sm font-medium">
                            {getPasswordStrengthText()}
                          </span>
                        </div>
                        <div className="w-full bg-gray-200 rounded-full h-2">
                          <div
                            className={cn('h-2 rounded-full transition-all duration-300', getPasswordStrengthColor())}
                            style={{ width: `${(passwordStrength / 6) * 100}%` }}
                          />
                        </div>
                      </div>
                    )}
                  </div>
                  <Input
                    label="Confirm Password"
                    type="password"
                    placeholder="Confirm your password"
                    {...register('confirmPassword')}
                    error={errors.confirmPassword?.message}
                  />
                  <div className="bg-gray-50 dark:bg-gray-800 p-4 rounded-lg">
                    <h4 className="font-medium text-gray-900 dark:text-white mb-2">
                      Password Requirements:
                    </h4>
                    <ul className="text-sm text-gray-600 dark:text-gray-400 space-y-1">
                      <li className="flex items-center">
                        <svg className={cn('w-4 h-4 mr-2', password.length >= 8 ? 'text-success-500' : 'text-gray-400')} fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                        </svg>
                        At least 8 characters
                      </li>
                      <li className="flex items-center">
                        <svg className={cn('w-4 h-4 mr-2', /[a-z]/.test(password) ? 'text-success-500' : 'text-gray-400')} fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                        </svg>
                        One lowercase letter
                      </li>
                      <li className="flex items-center">
                        <svg className={cn('w-4 h-4 mr-2', /[A-Z]/.test(password) ? 'text-success-500' : 'text-gray-400')} fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                        </svg>
                        One uppercase letter
                      </li>
                      <li className="flex items-center">
                        <svg className={cn('w-4 h-4 mr-2', /[0-9]/.test(password) ? 'text-success-500' : 'text-gray-400')} fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                        </svg>
                        One number
                      </li>
                      <li className="flex items-center">
                        <svg className={cn('w-4 h-4 mr-2', /[^a-zA-Z0-9]/.test(password) ? 'text-success-500' : 'text-gray-400')} fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                        </svg>
                        One special character
                      </li>
                    </ul>
                  </div>
                  <div className="flex items-start">
                    <input
                      type="checkbox"
                      {...register('acceptTerms')}
                      className="mt-1 rounded border-gray-300 text-primary-600 focus:ring-primary-500"
                    />
                    <label className="ml-2 text-sm text-gray-600 dark:text-gray-400">
                      I accept the{' '}
                      <Link href="/terms" className="text-primary-600 hover:text-primary-500 dark:text-primary-400">
                        Terms and Conditions
                      </Link>{' '}
                      and{' '}
                      <Link href="/privacy" className="text-primary-600 hover:text-primary-500 dark:text-primary-400">
                        Privacy Policy
                      </Link>
                    </label>
                  </div>
                  {errors.acceptTerms && (
                    <p className="text-sm text-danger-600">{errors.acceptTerms.message}</p>
                  )}
                </div>
              )}

              {/* Navigation Buttons */}
              <div className="flex justify-between pt-6">
                <Button
                  type="button"
                  variant="outline"
                  onClick={currentStep === 1 ? () => router.push('/auth/login') : previousStep}
                  disabled={isLoading}
                >
                  {currentStep === 1 ? 'Back to Login' : 'Previous'}
                </Button>
                <Button
                  type={currentStep === 3 ? 'submit' : 'button'}
                  onClick={currentStep !== 3 ? nextStep : undefined}
                  loading={isLoading && currentStep === 3}
                  disabled={isLoading || (currentStep !== 3 && !isValid)}
                >
                  {currentStep === 3 ? (isLoading ? 'Creating Account...' : 'Create Account') : 'Next'}
                </Button>
              </div>
            </form>
          </FormProvider>
        </Card>

        {/* Footer */}
        <div className="mt-8 text-center text-sm text-gray-500 dark:text-gray-400">
          <p>&copy; 2024 TradePro. All rights reserved.</p>
        </div>
      </div>
    </div>
  )
}

// src/app/components/auth/register/register.component.ts
import { Component, Inject, PLATFORM_ID, Optional } from '@angular/core';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { ApiService } from '../../../services/api.service';

export interface Address {
  street: string;
  city: string;
  state: string;
  zipCode: string;
  country: string;
}

export interface RegisterRequest {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  phone: string;
  dateOfBirth: string;
  address: Address;
}

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatCardModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatSnackBarModule
  ],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  registerForm: FormGroup;
  isLoading = false;
  hidePassword = true;
  hideConfirmPassword = true;

  constructor(
    private fb: FormBuilder,
    private router: Router,
    @Optional() private snackBar: MatSnackBar,
    private apiService: ApiService,
    @Inject(PLATFORM_ID) private platformId: Object
  ) {
    this.registerForm = this.fb.group({
      firstName: ['', [Validators.required, Validators.minLength(2)]],
      lastName: ['', [Validators.required, Validators.minLength(2)]],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(8), Validators.pattern(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]/)]],
      confirmPassword: ['', Validators.required],
      phone: ['', [Validators.required, Validators.pattern(/^\+?[1-9]\d{1,14}$/)]],
      dateOfBirth: ['', [Validators.required, this.ageValidator]],
      address: this.fb.group({
        street: ['', Validators.required],
        city: ['', Validators.required],
        state: ['', Validators.required],
        zipCode: ['', [Validators.required, Validators.pattern(/^\d{5}(-\d{4})?$/)]],
        country: ['', Validators.required]
      })
    }, { validators: this.passwordMatchValidator });
  }

  ageValidator(control: any): { [key: string]: any } | null {
    if (!control.value) return null;
    
    const birthDate = new Date(control.value);
    const today = new Date();
    const age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();
    
    if (age < 18 || (age === 18 && monthDiff < 0)) {
      return { underage: true };
    }
    
    return null;
  }

  passwordMatchValidator(form: FormGroup): { [key: string]: any } | null {
    const password = form.get('password')?.value;
    const confirmPassword = form.get('confirmPassword')?.value;
    
    if (password !== confirmPassword) {
      return { passwordMismatch: true };
    }
    
    return null;
  }

  onSubmit(): void {
    if (this.registerForm.invalid) {
      this.registerForm.markAllAsTouched();
      return;
    }

    this.isLoading = true;
    
    const registerData: RegisterRequest = {
      firstName: this.registerForm.value.firstName,
      lastName: this.registerForm.value.lastName,
      email: this.registerForm.value.email,
      password: this.registerForm.value.password,
      phone: this.registerForm.value.phone,
      dateOfBirth: this.registerForm.value.dateOfBirth,
      address: this.registerForm.value.address
    };

    this.apiService.register(registerData).subscribe({
      next: (response) => {
        this.showSnackBar('Registration successful! Please login.');
        this.router.navigate(['/login']);
      },
      error: (error) => {
        console.error('Registration error:', error);
        this.showSnackBar(error.error?.message || 'Registration failed. Please try again.', 5000, ['error-snackbar']);
      },
      complete: () => {
        this.isLoading = false;
      }
    });
  }

  togglePasswordVisibility(field: 'password' | 'confirmPassword'): void {
    if (field === 'password') {
      this.hidePassword = !this.hidePassword;
    } else {
      this.hideConfirmPassword = !this.hideConfirmPassword;
    }
  }

  private showSnackBar(message: string, duration: number = 3000, panelClass: string[] = ['success-snackbar']): void {
    if (this.snackBar && isPlatformBrowser(this.platformId)) {
      this.snackBar.open(message, 'Close', {
        duration,
        panelClass
      });
    }
  }

  getErrorMessage(field: string): string {
    const control = this.registerForm.get(field);
    if (!control || !control.errors || !control.touched) return '';

    const errors = control.errors;
    
    if (errors['required']) return `${field.charAt(0).toUpperCase()}${field.slice(1)} is required`;
    if (errors['email']) return 'Please enter a valid email address';
    if (errors['minlength']) return `Minimum ${errors['minlength'].requiredLength} characters required`;
    if (errors['pattern']) {
      if (field === 'password') return 'Password must contain uppercase, lowercase, number and special character';
      if (field === 'phone') return 'Please enter a valid phone number';
      if (field === 'zipCode') return 'Please enter a valid ZIP code';
    }
    if (errors['underage']) return 'You must be at least 18 years old';
    if (field === 'confirmPassword' && this.registerForm.errors?.['passwordMismatch']) {
      return 'Passwords do not match';
    }
    
    return 'Invalid input';
  }
}

<div class="register-container">
  <div class="register-card">
    <mat-card class="card">
      <mat-card-header class="card-header">
        <mat-card-title class="card-title">
          <mat-icon class="title-icon">account_circle</mat-icon>
          Create Account
        </mat-card-title>
        <mat-card-subtitle class="card-subtitle">
          Join our trading platform today
        </mat-card-subtitle>
      </mat-card-header>

      <mat-card-content class="card-content">
        <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="register-form">
          <!-- Personal Information Section -->
          <div class="form-section">
            <h3 class="section-title">Personal Information</h3>
            <div class="form-row">
              <mat-form-field appearance="outline" class="form-field">
                <mat-label>First Name</mat-label>
                <input matInput formControlName="firstName" placeholder="Enter your first name">
                <mat-error *ngIf="registerForm.get('firstName')?.touched">
                  {{ getErrorMessage('firstName') }}
                </mat-error>
              </mat-form-field>

              <mat-form-field appearance="outline" class="form-field">
                <mat-label>Last Name</mat-label>
                <input matInput formControlName="lastName" placeholder="Enter your last name">
                <mat-error *ngIf="registerForm.get('lastName')?.touched">
                  {{ getErrorMessage('lastName') }}
                </mat-error>
              </mat-form-field>
            </div>

            <div class="form-row">
              <mat-form-field appearance="outline" class="form-field">
                <mat-label>Email Address</mat-label>
                <input matInput formControlName="email" placeholder="Enter your email address" type="email">
                <mat-icon matSuffix>email</mat-icon>
                <mat-error *ngIf="registerForm.get('email')?.touched">
                  {{ getErrorMessage('email') }}
                </mat-error>
              </mat-form-field>

              <mat-form-field appearance="outline" class="form-field">
                <mat-label>Phone Number</mat-label>
                <input matInput formControlName="phone" placeholder="Enter your phone number">
                <mat-icon matSuffix>phone</mat-icon>
                <mat-error *ngIf="registerForm.get('phone')?.touched">
                  {{ getErrorMessage('phone') }}
                </mat-error>
              </mat-form-field>
            </div>

            <mat-form-field appearance="outline" class="form-field full-width">
              <mat-label>Date of Birth</mat-label>
              <input matInput formControlName="dateOfBirth" type="date">
              <mat-icon matSuffix>cake</mat-icon>
              <mat-error *ngIf="registerForm.get('dateOfBirth')?.touched">
                {{ getErrorMessage('dateOfBirth') }}
              </mat-error>
            </mat-form-field>
          </div>

          <!-- Security Section -->
          <div class="form-section">
            <h3 class="section-title">Security</h3>
            <div class="form-row">
              <mat-form-field appearance="outline" class="form-field">
                <mat-label>Password</mat-label>
                <input matInput 
                       formControlName="password" 
                       [type]="hidePassword ? 'password' : 'text'" 
                       placeholder="Enter strong password">
                <button mat-icon-button matSuffix (click)="togglePasswordVisibility('password')" type="button">
                  <mat-icon>{{ hidePassword ? 'visibility_off' : 'visibility' }}</mat-icon>
                </button>
                <mat-error *ngIf="registerForm.get('password')?.touched">
                  {{ getErrorMessage('password') }}
                </mat-error>
              </mat-form-field>

              <mat-form-field appearance="outline" class="form-field">
                <mat-label>Confirm Password</mat-label>
                <input matInput 
                       formControlName="confirmPassword" 
                       [type]="hideConfirmPassword ? 'password' : 'text'" 
                       placeholder="Confirm your password">
                <button mat-icon-button matSuffix (click)="togglePasswordVisibility('confirmPassword')" type="button">
                  <mat-icon>{{ hideConfirmPassword ? 'visibility_off' : 'visibility' }}</mat-icon>
                </button>
                <mat-error *ngIf="registerForm.get('confirmPassword')?.touched">
                  {{ getErrorMessage('confirmPassword') }}
                </mat-error>
              </mat-form-field>
            </div>
          </div>

          <!-- Address Section -->
          <div class="form-section">
            <h3 class="section-title">Address Information</h3>
            <div formGroupName="address">
              <mat-form-field appearance="outline" class="form-field full-width">
                <mat-label>Street Address</mat-label>
                <input matInput formControlName="street" placeholder="123 Main St">
                <mat-icon matSuffix>home</mat-icon>
                <mat-error *ngIf="registerForm.get('address.street')?.touched && registerForm.get('address.street')?.invalid">
                  Street address is required
                </mat-error>
              </mat-form-field>

              <div class="form-row">
                <mat-form-field appearance="outline" class="form-field">
                  <mat-label>City</mat-label>
                  <input matInput formControlName="city" placeholder="New York">
                  <mat-error *ngIf="registerForm.get('address.city')?.touched && registerForm.get('address.city')?.invalid">
                    City is required
                  </mat-error>
                </mat-form-field>

                <mat-form-field appearance="outline" class="form-field">
                  <mat-label>State</mat-label>
                  <input matInput formControlName="state" placeholder="NY">
                  <mat-error *ngIf="registerForm.get('address.state')?.touched && registerForm.get('address.state')?.invalid">
                    State is required
                  </mat-error>
                </mat-form-field>
              </div>

              <div class="form-row">
                <mat-form-field appearance="outline" class="form-field">
                  <mat-label>ZIP Code</mat-label>
                  <input matInput formControlName="zipCode" placeholder="10001">
                  <mat-error *ngIf="registerForm.get('address.zipCode')?.touched">
                    {{ getErrorMessage('zipCode') }}
                  </mat-error>
                </mat-form-field>

                <mat-form-field appearance="outline" class="form-field">
                  <mat-label>Country</mat-label>
                  <input matInput formControlName="country" placeholder="USA">
                  <mat-error *ngIf="registerForm.get('address.country')?.touched && registerForm.get('address.country')?.invalid">
                    Country is required
                  </mat-error>
                </mat-form-field>
              </div>
            </div>
          </div>

          <div class="form-actions">
            <button mat-raised-button 
                    type="submit" 
                    color="primary" 
                    class="submit-btn"
                    [disabled]="registerForm.invalid || isLoading">
              <mat-icon *ngIf="!isLoading">person_add</mat-icon>
              <mat-spinner *ngIf="isLoading" diameter="20" class="spinner"></mat-spinner>
              {{ isLoading ? 'Creating Account...' : 'Create Account' }}
            </button>
          </div>
        </form>
      </mat-card-content>

      <mat-card-actions class="card-actions">
        <p class="login-prompt">
          Already have an account? 
          <a routerLink="/login" class="login-link">Sign In</a>
        </p>
      </mat-card-actions>
    </mat-card>
  </div>
</div>
